FlagAI-Open/FlagAI

- docs/TUTORIAL_1_TOKENIZER.md
Signed-off-by: ZhaodongYan1 <yzdrogeryan@gmail.com>
> removed ch links in eng docs

- .github/workflows/python-publish.yml
- setup.py
1. Added a new action which can automatically publish flagai after pushing to Github: It will fist upload to testpypi and if success, upload to pypi 
2. Moved the required packages list to setup.py
> enable automatic publish process

- flagai/model/bert_model.py
> fix_bert4mlm

- examples/cpm_1/generate.py
> fix_cpm_model_name

- setup.py
Signed-off-by: Anhforth <yanzhaodong2021@163.com>
> Updated the release version

- CONTRIBUTING.md
- README.md
- README_zh.md
- SUPPORT.md
- doc_zh/TUTORIAL_4_TRAINER.md
- doc_zh/TUTORIAL_5_INSTRUCTIONS_FOR_AutoLoader.md
- doc_zh/TUTORIAL_9_SEQ2SEQ_METHOD.md
- docs/TUTORIAL_4_TRAINER.md
- docs/TUTORIAL_5_INSTRUCTIONS_FOR_AutoLoader.md
- docs/TUTORIAL_9_SEQ2SEQ_METHOD.md
- setup.py
corresponding changes in the MD files.
> Change the BAAI-Open into FlagAI-Open

- examples/AltCLIP/AltCLIP_evaluation.py
- examples/AltCLIP/README.md
- examples/AltCLIP/altclip_finetuning.py
- examples/AltCLIP/altclip_inference.py
- examples/AltCLIP/zeroshot_classification.py
> add readme file for AltCLIP

- flagai/auto_model/auto_loader.py
- flagai/model/mm/AltCLIP.py
> modify classnames

- examples/AltCLIP/README.md
> modify readme.md of AltCLIP

- README.md
- README_zh.md
- examples/AltCLIP/README.md
- examples/AltDiffusion/README.md
Add reference and  instructions for AltCLIP and AltDiffusion
> add references and instructions for AltCLIP and AltDiffusion

- examples/AltCLIP/README.md
- quickstart/glm_blank_filling_QA_ch.py
> Fix readme file and issue_99

- flagai/auto_model/auto_loader.py
> add M9 model to autoloader

- examples/AltDiffusion/README.md
1. Added m9 information on top
2. Simplified descriptions in readme
> Add m9 information on top

- flagai/model/base_model.py
- flagai/model/mm/AltCLIP.py
- flagai/model/mm/AltDiffusion.py
- flagai/model/predictor/predictor.py
> fix device bug of AltDiffusion

- README.md
- README_zh.md
- quickstart/texttoimage_generation.py
Signed-off-by: BAAI-OpenPlatform <open.platform@baai.ac.cn>
> added quickstart

- README.md
- README_zh.md
> ADD eva-clip to REAME

- flagai/auto_model/auto_loader.py
> load model no network

- flagai/auto_model/auto_loader.py
> download_file_name_err

- flagai/model/mm/AltDiffusion.py
- flagai/model/mm/Sampler.py
> fix altdiffusion cpu load err

- flagai/trainer.py
> fix vit validation bug

- flagai/env_args.py
Signed-off-by: ldwang <ldwang@baai.ac.cn>
> up env_args fix arg_add when store_true=True

- examples/AltCLIP/README.md
- examples/AltCLIP/altclip_finetuning.py
- examples/AltCLIP/altclip_inference.py
> fix altclip's bug of inference

- flagai/launch.py
> improve lanuch

- flagai/launch.py
Reverts FlagAI-Open/FlagAI#191
> Revert "improve lanuch"

- flagai/launch.py
- flagai/model/file_utils.py
> modify launch

- examples/EVA_CLIP/README.md
> add benchmarks and model link for eva-clip

- examples/AltCLIP/README.md
- examples/glm_blank_filling/glm_generate_samples.py
- flagai/model/file_utils.py
Signed-off-by: Anhforth <yanzaodong2021@163.com>
---
title: '[PR]'
---
> fix typo and checkpoint downloading issue

- flagai/model/gpt2_model.py
- flagai/model/opt_model.py
> fix opt load bug

- flagai/logger.py
Signed-off-by: shunxing1234 <xw747777271@gmail.com>
---
title: '[PR]'
---
> add bmt init

- flagai/env_args.py
- flagai/env_trainer_v1.py
- flagai/trainer_v1.py
Signed-off-by: ftgreat <ftgreat@163.com>
---
title: '[PR]'
---
> add wandb and update trainer_v1

- examples/gpt3_pretrain/train_env_xl_bmtrain_debug_rank_split.py
Signed-off-by: ftgreat <ftgreat@163.com>
---
title: '[PR]'
---
> add rank_split example

- examples/gpt3_pretrain/train_env_xl_bmtrain_gpt2_xl.py
Signed-off-by: ftgreat <ftgreat@163.com>
---
title: '[PR]'
---
> up gpt2_xl script

- examples/gpt3_pretrain/gpm/config.json
- examples/gpt3_pretrain/gpm/config.json.13b
- flagai/env_trainer_v1.py
- flagai/trainer_v1.py
> gpm dev add ppl

- flagai/env_trainer_v1.py
- flagai/trainer_v1.py
> gpm dev add ppl & cases

- flagai/env_args.py
- flagai/env_trainer_v1.py
- flagai/trainer_v1.py
> support already_fp16 training

- examples/galactica/generate_galactica_1.3b.py
- flagai/auto_model/auto_loader.py
- flagai/data/tokenizer/galactica/galactica_tokenizer.py
- flagai/model/galactica_model.py
- flagai/model/predictor/predictor.py
---
title: '[PR]'
---
Add galactica model for flagai
new feature provided
> add galactica model

- flagai/env_trainer_v1.py
- flagai/trainer_v1.py
> disable wandb

- flagai/env_args.py
- flagai/env_trainer_v1.py
- flagai/trainer_v1.py
- flagai/utils.py
> update save_optim & load_optim

- flagai/env_args.py
- flagai/env_trainer_v1.py
- flagai/trainer_v1.py
> support resume dataset

- examples/llama/llama_13b_generate.py
- examples/llama/llama_33b_generate.py
- examples/llama/llama_65b_generate.py
- examples/llama/llama_7b_generate.py
- examples/llama/llama_generate.py
- flagai/auto_model/auto_loader.py
- flagai/data/tokenizer/llama/tokenizer.py
- flagai/model/base_model.py
- flagai/model/llama.py
- flagai/model/predictor/llama.py
- flagai/model/predictor/predictor.py
- flagai/mp_tools.py
- flagai/tools/merge_huggingface_weight.py
---
title: 'llama model'
---
I add a new model (llama) to the FlagAI.
- new feature provided
> add llama model

- examples/gpt3_pretrain/build_index_mappings.py
- flagai/env_trainer_v1.py
- flagai/trainer_v1.py
> add weighted blended datasets

- examples/gpt3_pretrain/generate.py
- flagai/env_args.py
- flagai/env_trainer_v1.py
- flagai/trainer_v1.py
> add wandb key & dir

- flagai/model/layers/attentions.py
> up GPT2Attention c_proj init func

- script/merge_datasets.py
- script/preprocess_data_flagai_args.py
> add preprocess_data_flagai_args merge_datasets tools

- flagai/model/predictor/gpt.py
> remove eos in gpt predictor

- .gitignore
- examples/bminf_generate/glm_generate.py
- flagai/trainer.py
> Fix issue262

- doc_zh/TUTORIAL_21_OPTIMIZER.md
- docs/TUTORIAL_21_OPTIMIZER.md
> add optimizer tutorial

- examples/gpt3_pretrain/train_env_xl_bmtrain_gpt2_base_weighted_datasets.py
> weighted_datasets demo

- examples/gpt3_pretrain/build_index_mappings.py
- examples/gpt3_pretrain/train_env_xl_bmtrain_gpt2_base_weighted_datasets.py
> up weighted_datasets demo

- examples/gpt3_pretrain/build_index_mappings.py
- examples/gpt3_pretrain/build_weighted_datasets.py
> add build_weighted_datasets.py

- flagai/env_trainer_v1.py
- flagai/trainer_v1.py
> fix data_loader sampler for ds&mpu

- .github/ISSUE_TEMPLATE/bug-report.yml
---
title: '[PR]'
---
fix issue template bug-report.yml
> fix issue template bug-report.yml

- README.md
- README_zh.md
- setup.py
> Update version to 1.6.3

- README.md
- README_zh.md
- examples/Aquila/Aquila-chat/README.md
- examples/Aquila/Aquila-code/README.md
- examples/Aquila/Aquila-pretrain/README.md
- examples/Aquila/README.md
> Merge aquila

- .github/workflows/python-app.yml
> Update python-app.yml to python 3.8

- flagai/data/tokenizer/uni_tokenizer/tokenizer.py
> fixed issue 337

- examples/Aquila/Aquila-chat/generate_chat_bminf.py
> updated path

- examples/Aquila/Aquila-code/README.md
> updated code docs

- setup.py
> version updated

- flagai/fp16/fp16util.py
---
title: 'Fix typo in fp16util.py'
---
recieved -> received
> Fix typo in fp16util.py

- flagai/mpu/grads.py
---
title: '[PR]'
---
when torch.__version__ >=2, sys should be imported.
- [Y ] bug fixed
> [FIX_BUG] when torch.__version__ >=2, sys should be imported

- examples/Aquila/Aquila-code/aquila_code_pretrain.py
- examples/Aquila/Aquila-pretrain/aquila_pretrain.py
- examples/Aquila/aquila_pretrain.py
> Fix typo in aquila_pretrain.py

- examples/Aquila/Aquila-pretrain/generate.py
- flagai/model/predictor/aquila.py
> fix multinomial inf

- flagai/model/predictor/aquila.py
- flagai/model/predictor/predictor.py
> add topk arg

- flagai/model/layers/attentions.py
> try to fix inf

- flagai/data/tokenizer/uni_tokenizer/tokenizer.py
- flagai/model/predictor/aquila.py
> remove unnecessary print

- examples/Aquila/Aquila-pretrain/dist_trigger_docker.sh
- examples/Aquila/dist_trigger_docker.sh
> updated dist_trigger_docker

- examples/Aquila/Aquila-chat/README.md
- examples/Aquila/Aquila-code/README.md
- examples/Aquila/Aquila-pretrain/README.md
- examples/Aquila/README.md
> updated doc reference

- script/make_conversations_v3.py
> add make_conversations_v3.py

- setup.py
> updated yaml version

- examples/Aquila/Aquila-server/aquila_server.py
- examples/Aquila/Aquila-server/cyg_conversation.py
- examples/Aquila/Aquila-server/post_request.py
- examples/Aquila/test/test_eval_gsm.py
- examples/Aquila/test/test_eval_mmlu.py
- flagai/model/predictor/aquila_server.py
---
title: '[PR]'
---
new feature provided
> add aquila-server code

- examples/Aquila/Aquila-chat/README.md
- examples/Aquila/Aquila-chat/README_en.md
- examples/Aquila/Aquila-code/README.md
- examples/Aquila/Aquila-code/README_en.md
- examples/Aquila/Aquila-pretrain/README.md
- examples/Aquila/Aquila-pretrain/README_en.md
- examples/Aquila/README.md
- examples/Aquila/README_en.md
> added change log for docs

- flagai/model/base_model.py
> rechanged autoloader

- examples/Aquila/Aquila-chat/README.md
- examples/Aquila/Aquila-chat/README_en.md
- examples/Aquila/Aquila-chat/generate_chat_bminf.py
- examples/Aquila/Aquila-code/README.md
- examples/Aquila/Aquila-code/README_en.md
- examples/Aquila/Aquila-code/generate_code_bminf.py
- examples/Aquila/Aquila-pretrain/README.md
- examples/Aquila/Aquila-pretrain/README_en.md
- examples/Aquila/Aquila-pretrain/generate_bminf.py
- examples/Aquila/README.md
- examples/Aquila/README_en.md
- examples/Aquila/generate_bminf.py
> add docs for lora generate and hostfile setup

- examples/Aquila/Aquila-chat/README.md
- examples/Aquila/Aquila-chat/README_en.md
- examples/Aquila/Aquila-code/README.md
- examples/Aquila/Aquila-code/README_en.md
- examples/Aquila/Aquila-pretrain/README.md
- examples/Aquila/Aquila-pretrain/README_en.md
- examples/Aquila/README.md
- examples/Aquila/README_en.md
- examples/Aquila/changelog.md
- examples/Aquila/changelog_zh.md
> updated change log

- Dockerfile
> Update Dockerfile to support build a docker image for training.

- examples/Aquila/Aquila-chat/README.md
- examples/Aquila/Aquila-pretrain/README.md
- examples/Aquila/README.md
- setup.py
> updated docs

- examples/Aquila/Aquila-chat/README.md
- examples/Aquila/Aquila-chat/README_en.md
- examples/Aquila/Aquila-code/README.md
- examples/Aquila/Aquila-code/README_en.md
- examples/Aquila/Aquila-pretrain/README.md
- examples/Aquila/Aquila-pretrain/README_en.md
- examples/Aquila/README.md
- examples/Aquila/README_en.md
> change log doc updated

- examples/Aquila/Aquila-server/aquila_server.py
> add filter for model output

- flagai/env_args.py
> modified an argument type

- examples/Aquila/Aquila-pretrain/generate.py
- examples/Aquila/generate.py
> changed to cuda loading for Aquila base model

- examples/Aquila/Aquila-chat/README.md
- examples/Aquila/Aquila-chat/README_en.md
- examples/Aquila/Aquila-code/README.md
- examples/Aquila/Aquila-code/README_en.md
- examples/Aquila/Aquila-pretrain/README.md
- examples/Aquila/Aquila-pretrain/README_en.md
- examples/Aquila/README.md
- examples/Aquila/README_en.md
- examples/Aquila/changelog.md
- examples/Aquila/changelog_zh.md
> docs update for new model version

- examples/Aquila/Aquila-server/Aquila-multigpu-infer/aquilachat-7b-multigpu-infer.py
- examples/Aquila/Aquila-server/Aquila-multigpu-infer/cyg_conversation.py
> add aquilachat model for multigpu inference

- examples/Aquila/Aquila-chat/README.md
- examples/Aquila/Aquila-chat/README_en.md
- examples/Aquila/Aquila-code/README.md
- examples/Aquila/Aquila-code/README_en.md
- examples/Aquila/README.md
- examples/Aquila/README_en.md
> fix readme

- flagai/model/predictor/aquila_server.py
> fix messy code bug

- flagai/model/predictor/aquila_server.py
> fix messy code

- requirements.txt
> add requirements.txt for Dockerfile

- script/convert_aquila_weights_to_hf.py
> add aquila flagai2hf weight script

- examples/Aquila/Aquila-chat/aquila_chat.py
- examples/Aquila/Aquila-code/aquila_code_pretrain.py
- examples/Aquila/Aquila-pretrain/aquila_pretrain.py
- examples/Aquila/Aquila-sql/aquila_sql_flash.py
- examples/Aquila/aquila_pretrain.py
- setup.py
> fixed yaml setup issue

- .github/workflows/openhands-resolver.yml
> Add OpenHands resolver workflow configuration
